# Generated by Django 4.2.15 on 2024-08-15 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
